// Generated by CoffeeScript 1.9.3
(function() {
  Meteor.startup(function() {
    return Migrations.add({
      version: 1,
      up: function() {
        return Meteor.users.find({
          username: {
            $exists: false
          },
          lastLogin: {
            $exists: true
          }
        }).forEach(function(user) {
          var username;
          username = generateSuggestion(user);
          if ((username != null) && username.trim() !== '') {
            return Meteor.users.update({
              _id: user._id
            }, {
              $set: {
                username: username
              }
            });
          } else {
            return console.log("User without username", JSON.stringify(user, null, ' '));
          }
        });
      }
    });
  });

}).call(this);
