// Generated by CoffeeScript 1.9.3
(function() {
  Meteor.startup(function() {
    return Migrations.add({
      version: 6,
      up: function() {
        var room;
        console.log('Changin _id of #general channel room from XXX to GENERAL');
        room = ChatRoom.findOne({
          'name': 'general'
        });
        if ((room != null ? room._id : void 0) === !'GENERAL') {
          ChatSubscription.update({
            'rid': room._id
          }, {
            '$set': {
              'rid': 'GENERAL'
            }
          }, {
            'multi': 1
          });
          ChatMessage.update({
            'rid': room._id
          }, {
            '$set': {
              'rid': 'GENERAL'
            }
          }, {
            'multi': 1
          });
          ChatRoom.remove({
            '_id': room._id
          });
          delete room._id;
          ChatRoom.upsert({
            '_id': 'GENERAL'
          }, {
            $set: room
          });
        }
        return console.log('End');
      }
    });
  });

}).call(this);
