// Generated by CoffeeScript 1.9.3
(function() {
  Meteor.startup(function() {
    return Migrations.add({
      version: 7,
      up: function() {
        var count, query;
        console.log('Populate urls in messages');
        query = ChatMessage.find({
          'urls.0': {
            $exists: true
          }
        });
        count = query.count();
        query.forEach(function(message, index) {
          console.log((index + 1) + " / " + count);
          message.urls = message.urls.map(function(url) {
            if (_.isString(url)) {
              return {
                url: url
              };
            }
            return url;
          });
          return OEmbed.RocketUrlParser(message);
        });
        return console.log('End');
      }
    });
  });

}).call(this);
