// Generated by CoffeeScript 1.9.3
(function() {
  Meteor.startup(function() {
    return Meteor.defer(function() {
      var control;
      if (Migrations.getVersion() !== 0) {
        return Migrations.migrateTo('latest');
      } else {
        control = Migrations._getControl();
        control.version = _.last(Migrations._list).version;
        return Migrations._setControl(control);
      }
    });
  });

}).call(this);
