// Generated by CoffeeScript 1.9.3
(function() {
  Meteor.methods({
    saveRoomName: function(rid, name) {
      var ref, room;
      if (!Meteor.userId()) {
        throw new Meteor.Error(203, t('User_logged_out'));
      }
      room = ChatRoom.findOne(rid);
      if (room.u._id !== Meteor.userId() || ((ref = room.t) !== 'c' && ref !== 'p')) {
        throw new Meteor.Error(403, t('Not allowed'));
      }
      name = _.slugify(name);
      if (name === room.name) {
        return;
      }
      ChatRoom.update(rid, {
        $set: {
          name: name
        }
      });
      ChatSubscription.update({
        rid: rid
      }, {
        $set: {
          name: name
        }
      });
      return true;
    }
  });

}).call(this);
