// Generated by CoffeeScript 1.9.3
(function() {
  Meteor.methods({
    sendMessage: function(message) {
      if (!Meteor.userId()) {
        throw new Meteor.Error(203, t('User_logged_out'));
      }
      if (_.trim(message.msg) !== '') {
        message.ts = new Date(Date.now() + TimeSync.serverOffset());
        message.u = {
          _id: Meteor.userId(),
          username: Meteor.user().username
        };
        message = RocketChat.callbacks.run('beforeSaveMessage', message);
        return ChatMessageHistory.insert(message);
      }
    }
  });

}).call(this);
