// Generated by CoffeeScript 1.9.3
(function() {
  Meteor.methods({
    toogleFavorite: function(rid, f) {
      if (!Meteor.userId()) {
        throw new Meteor.Error(203, t('User_logged_out'));
      }
      return ChatSubscription.update({
        rid: rid,
        'u._id': Meteor.userId()
      }, {
        $set: {
          f: f
        }
      });
    }
  });

}).call(this);
