// Generated by CoffeeScript 1.9.3
(function() {
  Meteor.methods({
    updateMessage: function(message) {
      if (!Meteor.userId()) {
        throw new Meteor.Error(203, t('User_logged_out'));
      }
      return Tracker.nonreactive(function() {
        message.ets = new Date(Date.now() + TimeSync.serverOffset());
        message = RocketChat.callbacks.run('beforeSaveMessage', message);
        return ChatMessageHistory.update({
          _id: message.id,
          'u._id': Meteor.userId()
        }, {
          $set: {
            ets: message.ets,
            msg: message.msg
          }
        });
      });
    },
    deleteMessage: function(message) {
      if (!Meteor.userId()) {
        throw new Meteor.Error(203, t('general.User_logged_out'));
      }
      return Tracker.nonreactive(function() {
        return ChatMessageHistory.remove({
          _id: message.id,
          'u._id': Meteor.userId()
        });
      });
    }
  });

}).call(this);
