// Generated by CoffeeScript 1.9.3
(function() {
  Meteor.publish('activeUsers', function() {
    if (!this.userId) {
      return this.ready();
    }
    console.log('[publish] activeUsers'.green);
    return Meteor.users.find({
      username: {
        $exists: 1
      },
      status: {
        $in: ['online', 'away', 'busy']
      }
    }, {
      fields: {
        username: 1,
        status: 1
      }
    });
  });

}).call(this);
