// Generated by CoffeeScript 1.9.3
(function() {
  Meteor.publish('messages', function(rid, start) {
    var cursor, cursorDelete, cursorDeleteHandle, cursorHandle, publication;
    if (!this.userId) {
      return this.ready();
    }
    publication = this;
    console.log('[publish] messages ->'.green, 'rid:', rid, 'start:', start);
    if (typeof rid !== 'string') {
      return this.ready();
    }
    if (!Meteor.call('canAccessRoom', rid, this.userId)) {
      return this.ready();
    }
    cursor = ChatMessage.find({
      rid: rid,
      _deleted: {
        $ne: true
      }
    }, {
      sort: {
        ts: -1
      },
      limit: 50
    });
    cursorHandle = cursor.observeChanges({
      added: function(_id, record) {
        return publication.added('rocketchat_message', _id, record);
      },
      changed: function(_id, record) {
        return publication.changed('rocketchat_message', _id, record);
      }
    });
    cursorDelete = ChatMessage.find({
      rid: rid,
      _deleted: true
    }, {
      fields: {
        _id: 1
      }
    });
    cursorDeleteHandle = cursorDelete.observeChanges({
      added: function(_id, record) {
        return publication.added('rocketchat_message', _id, {
          _deleted: true
        });
      },
      changed: function(_id, record) {
        return publication.added('rocketchat_message', _id, {
          _deleted: true
        });
      }
    });
    this.ready();
    return this.onStop(function() {
      cursorHandle.stop();
      return cursorDeleteHandle.stop();
    });
  });

}).call(this);
