// Generated by CoffeeScript 1.9.3
(function() {
  Meteor.publish('room', function(rid) {
    if (!this.userId) {
      return this.ready();
    }
    console.log('[publish] room ->'.green, 'arguments:', arguments);
    if (typeof rid !== 'string') {
      return this.ready();
    }
    if (!Meteor.call('canAccessRoom', rid, this.userId)) {
      return this.ready();
    }
    return ChatRoom.find({
      _id: rid
    }, {
      fields: {
        name: 1,
        t: 1,
        cl: 1,
        u: 1,
        usernames: 1
      }
    });
  });

}).call(this);
