// Generated by CoffeeScript 1.9.3
(function() {
  Meteor.publish('subscription', function() {
    if (!this.userId) {
      return this.ready();
    }
    console.log('[publish] subscription'.green);
    return ChatSubscription.find({
      'u._id': this.userId,
      open: true
    }, {
      fields: {
        t: 1,
        ts: 1,
        ls: 1,
        name: 1,
        rid: 1,
        f: 1,
        open: 1,
        alert: 1,
        unread: 1
      }
    });
  });

}).call(this);
