// Generated by CoffeeScript 1.9.3
(function() {
  Meteor.publish('userData', function() {
    if (!this.userId) {
      return this.ready();
    }
    console.log('[publish] userData'.green);
    return Meteor.users.find(this.userId, {
      fields: {
        name: 1,
        username: 1,
        status: 1,
        statusDefault: 1,
        statusConnection: 1,
        avatarOrigin: 1,
        admin: 1
      }
    });
  });

}).call(this);
