// Generated by CoffeeScript 1.9.3
(function() {
  Template.directMessages.helpers({
    rooms: function() {
      return ChatSubscription.find({
        t: {
          $in: ['d']
        },
        f: {
          $ne: true
        }
      }, {
        sort: {
          't': 1,
          'name': 1
        }
      });
    }
  });

  Template.directMessages.events({
    'click .add-room': function(e, instance) {
      SideNav.setFlex("directMessagesFlex");
      return SideNav.openFlex();
    }
  });

}).call(this);
