// Generated by CoffeeScript 1.9.3
(function() {
  Template.listChannelsFlex.helpers({
    channel: function() {
      var ref;
      return (ref = Template.instance().channelsList) != null ? ref.get() : void 0;
    }
  });

  Template.listChannelsFlex.events({
    'click header': function() {
      return SideNav.closeFlex();
    },
    'click .channel-link': function() {
      return SideNav.closeFlex();
    },
    'click footer .create': function() {
      return SideNav.setFlex("createChannelFlex");
    },
    'mouseenter header': function() {
      return SideNav.overArrow();
    },
    'mouseleave header': function() {
      return SideNav.leaveArrow();
    }
  });

  Template.listChannelsFlex.onCreated(function() {
    var instance;
    instance = this;
    instance.channelsList = new ReactiveVar([]);
    return Meteor.call('channelsList', function(err, result) {
      if (result) {
        return instance.channelsList.set(result.channels);
      }
    });
  });

}).call(this);
