// Generated by CoffeeScript 1.9.3
(function() {
  Template.privateGroups.helpers({
    tRoomMembers: function() {
      return t('Members_placeholder');
    },
    rooms: function() {
      return ChatSubscription.find({
        t: {
          $in: ['p']
        },
        f: {
          $ne: true
        }
      }, {
        sort: {
          't': 1,
          'name': 1
        }
      });
    }
  });

  Template.privateGroups.events({
    'click .add-room': function(e, instance) {
      SideNav.setFlex("privateGroupsFlex");
      return SideNav.openFlex();
    }
  });

}).call(this);
