// Generated by CoffeeScript 1.9.3
(function() {
  Template.starredRooms.helpers({
    rooms: function() {
      return ChatSubscription.find({
        f: true
      }, {
        sort: {
          't': 1,
          'name': 1
        }
      });
    },
    total: function() {
      return ChatSubscription.find({
        f: true
      }).count();
    }
  });

}).call(this);
