// Generated by CoffeeScript 1.9.3
(function() {
  Template.userSettingsFlex.helpers({
    languages: function() {
      var key, language, languages, result;
      languages = TAPi18n.getLanguages();
      result = [];
      for (key in languages) {
        language = languages[key];
        result.push(_.extend(language, {
          key: key
        }));
      }
      return _.sortBy(result, 'key');
    },
    userLanguage: function(key) {
      var ref;
      return ((ref = localStorage.getItem('userLanguage')) != null ? ref.split('-').shift().toLowerCase() : void 0) === key;
    }
  });

  Template.userSettingsFlex.events({
    'mouseenter header': function() {
      return SideNav.overArrow();
    },
    'mouseleave header': function() {
      return SideNav.leaveArrow();
    },
    'click header': function() {
      return SideNav.closeFlex();
    },
    'click .cancel-settings': function() {
      return SideNav.closeFlex();
    },
    'click .input-submit .save': function(e, instance) {
      var selectedLanguage;
      selectedLanguage = $('#language').val();
      if (localStorage.getItem('userLanguage') !== selectedLanguage) {
        localStorage.setItem('userLanguage', selectedLanguage);
        Meteor._reload.reload();
      }
      if ($('#password').val()) {
        Meteor.call('setPassword', $('#password').val(), function(err, results) {
          if (results) {
            toastr.success(t('Password_changed_successfully'));
          }
          if (err) {
            return toastr.error(error.reason);
          }
        });
      }
      SideNav.closeFlex();
      return instance.clearForm();
    }
  });

  Template.userSettingsFlex.onCreated(function() {
    var instance;
    instance = this;
    return this.clearForm = function() {
      instance.find('#language').value = localStorage.getItem('userLanguage');
      return instance.find('#password').value = '';
    };
  });

}).call(this);
