// Generated by CoffeeScript 1.9.3
(function() {
  Meteor.methods({
    addUserToRoom: function(data) {
      var fromId, newUser, now, room, update;
      fromId = Meteor.userId();
      room = ChatRoom.findOne(data.rid);
      if (room.u.username !== Meteor.user().username && room.t === 'c') {
        throw new Meteor.Error(403, '[methods] addUserToRoom -> Not allowed');
      }
      if (room.usernames.indexOf(data.username) !== -1) {
        return;
      }
      now = new Date();
      update = {
        $push: {
          usernames: {
            $each: [data.username],
            $sort: 1
          }
        }
      };
      newUser = Meteor.users.findOne({
        username: data.username
      });
      ChatRoom.update(data.rid, update);
      ChatSubscription.insert({
        rid: data.rid,
        ts: now,
        name: room.name,
        t: room.t,
        open: true,
        alert: true,
        unread: 1,
        u: {
          _id: newUser._id,
          username: data.username
        }
      });
      ChatMessage.insert({
        rid: data.rid,
        ts: now,
        t: 'au',
        msg: newUser.name,
        u: {
          _id: fromId,
          username: Meteor.user().username
        }
      });
      return true;
    }
  });

}).call(this);
