// Generated by CoffeeScript 1.9.3
(function() {
  Meteor.methods({
    channelsList: function() {
      return {
        channels: ChatRoom.find({
          t: 'c'
        }, {
          sort: {
            msgs: -1
          }
        }).fetch()
      };
    }
  });

}).call(this);
