// Generated by CoffeeScript 1.9.3
(function() {
  Meteor.methods({
    createDirectMessage: function(username) {
      var me, now, rid, to;
      if (!Meteor.userId()) {
        throw new Meteor.Error('invalid-user', "[methods] createDirectMessage -> Invalid user");
      }
      console.log('[methods] createDirectMessage -> '.green, 'userId:', Meteor.userId(), 'arguments:', arguments);
      me = Meteor.user();
      if (me.username === username) {
        return;
      }
      to = Meteor.users.findOne({
        username: username
      });
      if (!to) {
        throw new Meteor.Error('invalid-user', "[methods] createDirectMessage -> Invalid target user");
      }
      rid = [me._id, to._id].sort().join('');
      now = new Date();
      ChatRoom.upsert({
        _id: rid
      }, {
        $set: {
          usernames: [me.username, to.username]
        },
        $setOnInsert: {
          t: 'd',
          msgs: 0,
          ts: now
        }
      });
      ChatSubscription.upsert({
        rid: rid,
        $and: [
          {
            'u._id': me._id
          }
        ]
      }, {
        $set: {
          ts: now,
          ls: now
        },
        $setOnInsert: {
          name: to.username,
          t: 'd',
          open: true,
          alert: false,
          unread: 0,
          u: {
            _id: me._id,
            username: me.username
          }
        }
      });
      ChatSubscription.upsert({
        rid: rid,
        $and: [
          {
            'u._id': to._id
          }
        ]
      }, {
        $setOnInsert: {
          name: me.username,
          t: 'd',
          open: false,
          alert: false,
          unread: 0,
          u: {
            _id: to._id,
            username: to.username
          }
        }
      });
      return {
        rid: rid
      };
    }
  });

}).call(this);
