// Generated by CoffeeScript 1.9.3
(function() {
  Meteor.methods({
    eraseRoom: function(rid) {
      var fromId, userUnset;
      fromId = Meteor.userId();
      userUnset = {
        '$unset': {}
      };
      userUnset.$unset['readMessages.' + rid] = '';
      Meteor.users.update({
        _id: Meteor.userId()
      }, userUnset);
      ChatMessage.remove({
        rid: rid
      });
      return ChatRoom.remove(rid);
    }
  });

}).call(this);
