// Generated by CoffeeScript 1.9.3
(function() {
  Meteor.methods({
    hideRoom: function(rid) {
      if (!Meteor.userId()) {
        throw new Meteor.Error('invalid-user', '[methods] hideRoom -> Invalid user');
      }
      console.log('[methods] hideRoom -> '.green, 'userId:', Meteor.userId(), 'arguments:', arguments);
      return ChatSubscription.update({
        rid: rid,
        'u._id': Meteor.userId()
      }, {
        $set: {
          alert: false,
          open: false
        }
      });
    }
  });

}).call(this);
