// Generated by CoffeeScript 1.9.3
(function() {
  Meteor.methods({
    loadHistory: function(rid, end, limit, skip) {
      var fromId, options, query;
      if (limit == null) {
        limit = 20;
      }
      if (skip == null) {
        skip = 0;
      }
      fromId = Meteor.userId();
      query = {
        rid: rid,
        ts: {
          $lt: end
        }
      };
      options = {
        sort: {
          ts: -1
        },
        limit: limit,
        skip: skip
      };
      return ChatMessage.find(query, options).fetch();
    }
  });

}).call(this);
