// Generated by CoffeeScript 1.9.3
(function() {
  Meteor.methods({
    logoutCleanUp: function(user) {
      console.log('[methods] logoutCleanUp -> '.green, 'userId:', user._id);
      return Meteor.defer(function() {
        return RocketChat.callbacks.run('afterLogoutCleanUp', user);
      });
    }
  });

}).call(this);
