// Generated by CoffeeScript 1.9.3
(function() {
  Meteor.methods({
    readMessages: function(rid) {
      if (!Meteor.userId()) {
        throw new Meteor.Error('invalid-user', '[methods] readMessages -> Invalid user');
      }
      console.log('[methods] readMessages -> '.green, 'userId:', Meteor.userId(), 'arguments:', arguments);
      return ChatSubscription.update({
        rid: rid,
        'u._id': Meteor.userId()
      }, {
        $set: {
          open: true,
          alert: false,
          unread: 0,
          ls: new Date()
        }
      });
    }
  });

}).call(this);
