// Generated by CoffeeScript 1.9.3
(function() {
  Meteor.methods({
    registerUser: function(formData) {
      var userData, userId;
      userData = {
        email: formData.email,
        password: formData.pass
      };
      userId = Accounts.createUser(userData);
      Meteor.users.update(userId, {
        $set: {
          name: formData.name
        }
      });
      if (userData.email) {
        return Accounts.sendVerificationEmail(userId, userData.email);
      }
    }
  });

}).call(this);
