// Generated by CoffeeScript 1.9.3
(function() {
  Meteor.methods({
    removeRoom: function(rid) {
      var fromId;
      fromId = Meteor.userId();
      return ChatRoom.update({
        _id: rid
      }, {
        '$pull': {
          userWatching: Meteor.userId(),
          userIn: Meteor.userId()
        }
      });
    }
  });

}).call(this);
