// Generated by CoffeeScript 1.9.3
(function() {
  Meteor.methods({
    removeUserFromRoom: function(data) {
      var fromId, ref, removedUser, room, update;
      fromId = Meteor.userId();
      room = ChatRoom.findOne(data.rid);
      if (((ref = room.u) != null ? ref._id : void 0) !== Meteor.userId() && room.t === 'c') {
        throw new Meteor.Error(403, 'Not allowed');
      }
      update = {
        $pull: {
          usernames: data.username
        }
      };
      removedUser = Meteor.users.findOne({
        username: data.username
      });
      ChatRoom.update(data.rid, update);
      ChatSubscription.remove({
        'u._id': data.username,
        rid: data.rid
      });
      ChatMessage.insert({
        rid: data.rid,
        ts: new Date,
        t: 'ru',
        msg: removedUser.name,
        u: {
          _id: Meteor.userId(),
          username: Meteor.user().username
        }
      });
      return true;
    }
  });

}).call(this);
