// Generated by CoffeeScript 1.9.3
(function() {
  Meteor.methods({
    resetAvatar: function(image, service) {
      var user;
      if (!Meteor.userId()) {
        throw new Meteor.Error(403, "[methods] resetAvatar -> Invalid user");
      }
      console.log('[methods] resetAvatar -> '.green, 'userId:', Meteor.userId(), 'arguments:', arguments);
      user = Meteor.user();
      RocketChatFileAvatarInstance.deleteFile(user.username + ".jpg");
      Meteor.users.update(user._id, {
        $unset: {
          avatarOrigin: 1
        }
      });
    }
  });

}).call(this);
