// Generated by CoffeeScript 1.9.3
(function() {
  Meteor.methods({
    saveRoomName: function(rid, name) {
      var ref, room;
      if (!Meteor.userId()) {
        throw new Meteor.Error('invalid-user', "[methods] sendMessage -> Invalid user");
      }
      room = ChatRoom.findOne(rid);
      if (room.u._id !== Meteor.userId() || ((ref = room.t) !== 'c' && ref !== 'p')) {
        throw new Meteor.Error(403, 'Not allowed');
      }
      name = _.slugify(name);
      if (name === room.name) {
        return;
      }
      ChatRoom.update(rid, {
        $set: {
          name: name
        }
      });
      ChatSubscription.update({
        rid: rid
      }, {
        $set: {
          name: name,
          alert: true
        }
      }, {
        multi: true
      });
      ChatMessage.insert({
        rid: rid,
        ts: new Date,
        t: 'r',
        msg: name,
        u: {
          _id: Meteor.userId(),
          username: Meteor.user().username
        }
      });
      return true;
    }
  });

}).call(this);
