// Generated by CoffeeScript 1.9.3
(function() {
  Meteor.methods({
    sendForgotPasswordEmail: function(email) {
      var user;
      user = Meteor.users.findOne({
        'emails.address': email
      });
      if (user != null) {
        Accounts.sendResetPasswordEmail(user._id, email);
        return true;
      }
      return false;
    }
  });

}).call(this);
