// Generated by CoffeeScript 1.9.3
(function() {
  Meteor.methods({
    sendMessage: function(message) {
      var room, user;
      if (!Meteor.userId()) {
        throw new Meteor.Error('invalid-user', "[methods] sendMessage -> Invalid user");
      }
      console.log('[methods] sendMessage -> '.green, 'userId:', Meteor.userId(), 'arguments:', arguments);
      user = Meteor.users.findOne(Meteor.userId(), {
        fields: {
          username: 1
        }
      });
      room = Meteor.call('canAccessRoom', message.rid, user._id);
      if (!room) {
        return false;
      }
      return RocketChat.sendMessage(user, message, room);
    }
  });

}).call(this);
