// Generated by CoffeeScript 1.9.3
(function() {
  Meteor.methods({
    setAvatarFromService: function(dataURI, contentType, service) {
      var image, ref, rs, user, ws;
      if (!Meteor.userId()) {
        throw new Meteor.Error('invalid-user', "[methods] setAvatarFromService -> Invalid user");
      }
      console.log('[methods] setAvatarFromService -> '.green, 'userId:', Meteor.userId(), 'arguments:', arguments);
      user = Meteor.user();
      if (service === 'initials') {
        Meteor.users.update({
          _id: user._id
        }, {
          $set: {
            avatarOrigin: service
          }
        });
        return;
      }
      ref = RocketChatFile.dataURIParse(dataURI), image = ref.image, contentType = ref.contentType;
      rs = RocketChatFile.bufferToStream(new Buffer(image, 'base64'));
      ws = RocketChatFileAvatarInstance.createWriteStream(user.username + ".jpg", contentType);
      ws.on('end', Meteor.bindEnvironment(function() {
        return Meteor.users.update({
          _id: user._id
        }, {
          $set: {
            avatarOrigin: service
          }
        });
      }));
      rs.pipe(ws);
    }
  });

}).call(this);
