// Generated by CoffeeScript 1.9.3
(function() {
  Meteor.methods({
    setPassword: function(password) {
      if (Meteor.userId()) {
        Accounts.setPassword(Meteor.userId(), password, {
          logout: false
        });
        return true;
      }
    }
  });

}).call(this);
