// Generated by CoffeeScript 1.9.3
(function() {
  Template.avatar.helpers({
    imageUrl: function() {
      var ref, url, username;
      if (this.preventImage != null) {
        return;
      }
      username = this.username;
      if ((username == null) && (this.userId != null)) {
        username = (ref = Meteor.users.findOne(this.userId)) != null ? ref.username : void 0;
      }
      if (username == null) {
        return;
      }
      url = getAvatarUrlFromUsername(username);
      return "background-image:url(" + url + ");";
    }
  });

}).call(this);
