// Generated by CoffeeScript 1.9.3
(function() {
  Template.home.helpers({
    arrowPosition: function() {
      if (!Session.equals('flexOpened', true)) {
        return 'left';
      }
    },
    flexOpened: function() {
      if (Session.equals('flexOpened', true)) {
        return 'opened';
      }
    },
    withParagraph: function() {
      return {
        withParagraph: true
      };
    }
  });

  Template.home.events({
    "click .flex-tab .more": function(event) {
      return Session.set('flexOpened', !Session.get('flexOpened'));
    },
    "click .burger": function() {
      var chatContainer;
      chatContainer = $("#rocket-chat");
      if (chatContainer.hasClass("menu-closed")) {
        return chatContainer.removeClass("menu-closed").addClass("menu-opened");
      } else {
        return chatContainer.addClass("menu-closed").removeClass("menu-opened");
      }
    }
  });

}).call(this);
