// Generated by CoffeeScript 1.9.3
(function() {
  Template.appLayout.helpers({
    flexOpened: function() {
      if (window.rocketDebug) {
        console.log('layout.helpers flexOpened');
      }
      if (Session.equals('flexOpened', true)) {
        return 'flex-opened';
      }
    },
    flexOpenedRTC1: function() {
      if (window.rocketDebug) {
        console.log('layout.helpers flexOpenedRTC1');
      }
      if (Session.equals('rtcLayoutmode', 1)) {
        return 'layout1';
      }
    },
    flexOpenedRTC2: function() {
      if (window.rocketDebug) {
        console.log('layout.helpers flexOpenedRTC2');
      }
      if (Session.get('rtcLayoutmode') > 1) {
        return 'layout2';
      }
    }
  });

  Template.appLayout.rendered = function() {
    $('html').addClass("noscroll").removeClass("scroll");
    if (isRtl(localStorage.getItem("userLanguage"))) {
      return $('html').addClass("rtl");
    }
  };

}).call(this);
