// Generated by CoffeeScript 1.9.3
(function() {
  Template.messagePopupEmoji.helpers({
    value: function() {
      var length;
      length = this.data.length;
      return this.data[length - 1].toUpperCase();
    }
  });

}).call(this);
