// Generated by CoffeeScript 1.9.3
(function() {
  Template.privateHistory.helpers({
    history: function() {
      var items;
      items = ChatRoom.find({
        name: {
          $regex: Session.get('historyFilter'),
          $options: 'i'
        },
        t: {
          $in: ['d', 'c', 'p']
        }
      }, {
        'sort': {
          'ts': -1
        }
      });
      return {
        items: items,
        length: items.count()
      };
    },
    type: function() {
      switch (this.t) {
        case 'd':
          return 'icon-at';
        case 'c':
          return 'icon-hash';
        case 'p':
          return 'icon-lock';
      }
    },
    creation: function() {
      return moment(this.ts).format('LLL');
    },
    lastMessage: function() {
      if (this.lm) {
        return moment(this.lm).format('LLL');
      }
    }
  });

  Template.privateHistory.events({
    'keydown #history-filter': function(event) {
      if (event.which === 13) {
        event.stopPropagation();
        return event.preventDefault();
      }
    },
    'keyup #history-filter': function(event) {
      event.stopPropagation();
      event.preventDefault();
      return Session.set('historyFilter', event.currentTarget.value);
    }
  });

}).call(this);
