// Generated by CoffeeScript 1.9.3
(function() {
  Template.roomSearch.helpers({
    roomIcon: function() {
      if (this.type === 'u') {
        return 'icon-at';
      }
      if (this.type === 'r') {
        switch (this.t) {
          case 'd':
            return 'icon-at';
          case 'c':
            return 'icon-hash';
          case 'p':
            return 'icon-lock';
        }
      }
    },
    userStatus: function() {
      if (this.type === 'u') {
        return 'status-' + this.status;
      }
    }
  });

}).call(this);
