// Generated by CoffeeScript 1.9.3
(function() {
  this.typingStream = new Meteor.Stream('typing');

  typingStream.permissions.read(function() {
    return true;
  });

  typingStream.permissions.write(function() {
    return true;
  });

  typingStream.on('typing', function(typing) {
    return typingStream.emit(typing.room, _.pick(typing, 'username', 'start', 'stop'));
  });

}).call(this);
