// Generated by CoffeeScript 1.9.3
(function() {
  Meteor.startup(function() {
    return ChatRoom.find().observe({
      added: function(data) {
        return Session.set('roomData' + data._id, data);
      },
      changed: function(data) {
        return Session.set('roomData' + data._id, data);
      },
      removed: function(data) {
        return Session.set('roomData' + data._id, void 0);
      }
    });
  });

}).call(this);
