// Generated by CoffeeScript 1.9.3
(function() {
  var slice = [].slice;

  Meteor.startup(function() {
    var filename, userLanguage;
    UserPresence.awayTime = 300000;
    UserPresence.start();
    Meteor.subscribe("activeUsers");
    Session.setDefault('flexOpened', false);
    Session.setDefault('AvatarRandom', 0);
    window.lastMessageWindow = {};
    window.lastMessageWindowHistory = {};
    this.defaultUserLanguage = function() {
      var lng, re;
      lng = window.navigator.userLanguage || window.navigator.language || 'en';
      re = /([a-z]{2}-)([a-z]{2})/;
      if (re.test(lng)) {
        lng = lng.replace(re, function() {
          var match, parts;
          match = arguments[0], parts = 2 <= arguments.length ? slice.call(arguments, 1) : [];
          return parts[0] + parts[1].toUpperCase();
        });
      }
      return lng;
    };
    if (localStorage.getItem("userLanguage")) {
      userLanguage = localStorage.getItem("userLanguage");
    } else {
      userLanguage = defaultUserLanguage();
    }
    localStorage.setItem("userLanguage", userLanguage);
    userLanguage = userLanguage.split('-').shift();
    TAPi18n.setLanguage(userLanguage);
    filename = "/moment-locales/" + (userLanguage.toLowerCase()) + ".js";
    if (filename !== '/moment-locales/en.js') {
      return $.getScript(filename, function(data) {
        return moment.locale(userLanguage);
      });
    }
  });

}).call(this);
