// Generated by CoffeeScript 1.9.3
(function() {
  Meteor.startup(function() {
    return ChatSubscription.find({}, {
      fields: {
        unread: 1
      }
    }).observeChanges({
      changed: function(id, fields) {
        if (fields.unread && fields.unread > 0) {
          return KonchatNotification.newMessage();
        }
      }
    });
  });

  Meteor.startup(function() {
    return Tracker.autorun(function() {
      var i, len, ref, subscription, subscriptions, unreadAlert, unreadCount;
      unreadCount = 0;
      unreadAlert = false;
      subscriptions = ChatSubscription.find({}, {
        fields: {
          unread: 1,
          alert: 1
        }
      });
      ref = subscriptions.fetch();
      for (i = 0, len = ref.length; i < len; i++) {
        subscription = ref[i];
        unreadCount += subscription.unread;
        if (subscription.alert === true) {
          unreadAlert = '•';
        }
      }
      if (unreadCount > 0) {
        return Session.set('unread', unreadCount);
      } else if (unreadAlert !== false) {
        return Session.set('unread', unreadAlert);
      } else {
        return Session.set('unread', '');
      }
    });
  });

  Meteor.startup(function() {
    window.favico = new Favico({
      position: 'up',
      animation: 'none'
    });
    return Tracker.autorun(function() {
      var unread;
      unread = Session.get('unread');
      fireGlobalEvent('unread-changed', unread);
      if (typeof favico !== "undefined" && favico !== null) {
        favico.badge(unread, {
          bgColor: typeof unread !== 'number' ? '#3d8a3a' : '#ac1b1b'
        });
      }
      return document.title = unread === '' ? 'Rocket.Chat' : '(' + unread + ') Rocket.Chat';
    });
  });

}).call(this);
