// Generated by CoffeeScript 1.9.3
(function() {
  this.ChatMessage = new Meteor.Collection('rocketchat_message');

  this.ChatRoom = new Meteor.Collection('rocketchat_room');

  this.ChatSubscription = new Meteor.Collection('rocketchat_subscription');

}).call(this);
