// Generated by CoffeeScript 1.9.3
(function() {
  Meteor.startup(function() {
    if (RocketChat.settings.get('LDAP_URL')) {
      LDAP_DEFAULTS.url = RocketChat.settings.get('LDAP_URL');
      if (RocketChat.settings.get('LDAP_PORT')) {
        LDAP_DEFAULTS.port = RocketChat.settings.get('LDAP_PORT');
      }
      return LDAP_DEFAULTS.dn = RocketChat.settings.get('LDAP_DN' || false);
    }
  });

}).call(this);
