// Generated by CoffeeScript 1.9.3
(function() {
  Meteor.startup(function() {
    InstanceStatus.registerInstance('rocket.chat', {
      port: process.env.PORT
    });
    UserPresence.start();
    return UserPresenceMonitor.start();
  });

}).call(this);
