// Generated by CoffeeScript 1.9.3
(function() {
  this.AccountBox = (function() {
    var close, init, open, self, setStatus, status, toggle;
    status = 0;
    self = {};
    setStatus = function(status) {
      return Meteor.call('UserPresence:setDefaultStatus', status);
    };
    toggle = function() {
      if (status) {
        return close();
      } else {
        return open();
      }
    };
    open = function() {
      if (SideNav.flexStatus()) {
        SideNav.closeFlex();
        return;
      }
      status = 1;
      self.options.removeClass("_hidden");
      self.box.addClass("active");
      return SideNav.toggleArrow(1);
    };
    close = function() {
      status = 0;
      self.options.addClass("_hidden");
      self.box.removeClass("active");
      return SideNav.toggleArrow(-1);
    };
    init = function() {
      self.box = $(".account-box");
      return self.options = self.box.find(".options");
    };
    return {
      setStatus: setStatus,
      toggle: toggle,
      open: open,
      close: close,
      init: init
    };
  })();

}).call(this);
