// Generated by CoffeeScript 1.9.3
(function() {
  this.getAvatarUrlFromUsername = function(username) {
    var key, random;
    key = "avatar_random_" + username;
    random = Session.keys[key] || 0;
    if (username == null) {
      return;
    }
    return (Meteor.absoluteUrl()) + "avatar/" + username + ".jpg?_dc=" + random;
  };

  this.updateAvatarOfUsername = function(username) {
    var key, ref, room, url;
    key = "avatar_random_" + username;
    Session.set(key, Math.round(Math.random() * 1000));
    ref = RoomManager.openedRooms;
    for (key in ref) {
      room = ref[key];
      url = getAvatarUrlFromUsername(username);
      console.log(url);
      $(room.dom).find(".message[data-username='" + username + "'] .avatar-image").css('background-image', "url(" + url + ")");
    }
    return true;
  };

}).call(this);
