// Generated by CoffeeScript 1.9.3
(function() {
  this.UserAndRoom = new Meteor.Collection(null);

  this.ChatMessageHistory = new Meteor.Collection(null);

  this.ChatRoom = new Meteor.Collection('rocketchat_room');

  this.ChatSubscription = new Meteor.Collection('rocketchat_subscription');

}).call(this);
