// Generated by CoffeeScript 1.9.3
(function() {
  window.fireGlobalEvent = function(eventName, params) {
    return window.dispatchEvent(new CustomEvent(eventName, {
      detail: params
    }));
  };

}).call(this);
