// Generated by CoffeeScript 1.9.3
(function() {
  this.FlexTab = (function() {
    var check;
    check = function() {
      var $flex, $search, $siblings, width;
      $flex = $("section.flex-tab");
      if ($flex.length) {
        $search = $flex.find(".search-form");
        if ($search.length) {
          $siblings = $search.siblings("a");
          if ($siblings.length) {
            width = ($siblings.outerWidth() + $siblings.css("marginLeft").replace("px", "") * 2) * $siblings.length + 1;
            return $search.css({
              width: "calc(100% - " + width + "px)"
            });
          }
        }
      }
    };
    return {
      check: check
    };
  })();

}).call(this);
