// Generated by CoffeeScript 1.9.3
(function() {
  this.KonchatNotification = {
    getDesktopPermission: function() {
      if (window.Notification && Notification.permission !== "granted") {
        return Notification.requestPermission(function(status) {
          if (Notification.permission !== status) {
            return Notification.permission = status;
          }
        });
      }
    },
    showDesktop: function(room, msg) {
      var n, roomName;
      if (!Session.equals('user_' + Meteor.userId() + '_status', 'busy')) {
        roomName = room.name + ' - Rocket.Chat';
        if (window.Notification && Notification.permission === "granted") {
          n = new Notification(roomName, {
            icon: '/images/rocket-chat-logo-square.png',
            body: _.stripTags(msg)
          });
          n.onclick = function() {
            return $('#chat-window-' + room._id + '.chat-window .chat-title').click();
          };
          return setTimeout(function() {
            return n.close();
          }, 2000);
        }
      }
    },
    newMessage: function() {
      if (!Session.equals('user_' + Meteor.userId() + '_status', 'busy')) {
        return $('#chatAudioNotification')[0].play();
      }
    },
    newRoom: function(rid, withSound) {
      if (withSound == null) {
        withSound = true;
      }
      return Tracker.nonreactive(function() {
        var newRoomSound;
        newRoomSound = Session.get('newRoomSound');
        if (newRoomSound != null) {
          newRoomSound = _.union(newRoomSound, rid);
        } else {
          newRoomSound = [rid];
        }
        return Session.set('newRoomSound', newRoomSound);
      });
    },
    removeRoomNotification: function(rid) {
      Tracker.nonreactive(function() {
        var newRoomSound;
        newRoomSound = Session.get('newRoomSound');
        newRoomSound = _.without(newRoomSound, rid);
        return Session.set('newRoomSound', newRoomSound);
      });
      return $('.link-room-' + rid).removeClass('new-room-highlight');
    }
  };

  Tracker.autorun(function() {
    var ref;
    if (((ref = Session.get('newRoomSound')) != null ? ref.length : void 0) > 0) {
      if (!Session.equals('user_' + Meteor.userId() + '_status', 'busy')) {
        return $('#chatNewRoomNotification').each(function() {
          return this.play();
        });
      }
    } else {
      return $('#chatNewRoomNotification').each(function() {
        this.pause();
        return this.currentTime = 0;
      });
    }
  });

}).call(this);
