// Generated by CoffeeScript 1.9.3
(function() {
  var slice = [].slice;

  this.t = function() {
    var key, replaces;
    key = arguments[0], replaces = 2 <= arguments.length ? slice.call(arguments, 1) : [];
    if (_.isObject(replaces[0])) {
      return TAPi18n.__(key, replaces);
    } else {
      return TAPi18n.__(key, {
        postProcess: 'sprintf',
        sprintf: replaces
      });
    }
  };

  this.tr = function() {
    var key, options, replaces;
    key = arguments[0], options = arguments[1], replaces = 3 <= arguments.length ? slice.call(arguments, 2) : [];
    if (_.isObject(replaces[0])) {
      return TAPi18n.__(key, options, replaces);
    } else {
      return TAPi18n.__(key, options, {
        postProcess: 'sprintf',
        sprintf: replaces
      });
    }
  };

  this.isRtl = function(language) {
    var ref;
    return (ref = language.split('-').shift().toLowerCase()) === 'ar' || ref === 'dv' || ref === 'fa' || ref === 'he' || ref === 'ku' || ref === 'ps' || ref === 'sd' || ref === 'ug' || ref === 'ur' || ref === 'yi';
  };

}).call(this);
