// Generated by CoffeeScript 1.9.3
(function() {
  Template.loginFooter.helpers({
    LanguageVersion: function() {
      if (Template.instance().languageVersion.get()) {
        return TAPi18next.t('project:Language_Version', {
          lng: Template.instance().languageVersion.get()
        });
      }
    }
  });

  Template.loginFooter.events({
    'click a.switch-language': function(e, t) {
      var userLanguage;
      userLanguage = t.languageVersion.get();
      localStorage.setItem("userLanguage", userLanguage);
      TAPi18n.setLanguage(userLanguage);
      moment.locale(userLanguage);
      return t.languageVersion.set(userLanguage !== defaultUserLanguage() ? defaultUserLanguage() : 'en');
    }
  });

  Template.loginFooter.onCreated(function() {
    var self, userLanguage;
    self = this;
    this.languageVersion = new ReactiveVar;
    userLanguage = localStorage.getItem('userLanguage');
    if (userLanguage !== defaultUserLanguage()) {
      return TAPi18n._loadLanguage(defaultUserLanguage()).done(function() {
        return self.languageVersion.set(defaultUserLanguage());
      });
    } else if (userLanguage.indexOf('en') !== 0) {
      return TAPi18n._loadLanguage('en').done(function() {
        return self.languageVersion.set('en');
      });
    }
  });

}).call(this);
