// Generated by CoffeeScript 1.9.3
(function() {
  Template.loginLayout.rendered = function() {
    $('html').addClass("scroll").removeClass("noscroll");
    return particlesJS.load('particles-js', '/scripts/particles.json', function() {});
  };

}).call(this);
